version: '3.8'

services:
  web:
    build: .
    container_name: blog2025-web
    command: gunicorn blog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles  # Archivos est√°ticos compartidos
      - ./media:/app/media             # Archivos media compartidos
    depends_on:
      - db
    expose:
      - "8000"

  db:
    image: postgres:15
    container_name: blog2025-db
    environment:
      POSTGRES_DB: db_blog2025
      POSTGRES_USER: russell
      POSTGRES_PASSWORD: russell2020
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: blog2025-nginx
    ports:
      - "8000:80"  # Mapea puerto 80 de Nginx al 8000 del host
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/staticfiles
      - ./media:/media
    depends_on:
      - web

volumes:
  pgdata:
